# Gunakan image PHP dengan Apache
FROM php:8.1-apache

# Pastikan Apache diarahkan ke folder /var/www/html (default)
WORKDIR /var/www/html

# Aktifkan modul PHP yang diperlukan (contoh: mysqli)
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Berikan izin untuk folder public
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html

# Expose port 80 untuk Apache
EXPOSE 80

# Jalankan Apache
CMD ["apache2-foreground"]
